package org.unibl.etf.testiranje;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AzuriranjeStudentaTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void azuriranjeStudenta() {
 driver.get("http://localhost:4200/view-student");
 driver.manage().window().setSize(new Dimension(890, 728));
 driver.findElement(By.cssSelector(".odd:nth-child(1) .btn-info")).click();
 driver.findElement(By.xpath("//*[@id=\"myModal\"]/div/div/form/div[2]/div[1]/div[1]/input")).click();
 driver.findElement(By.xpath("//*[@id=\"myModal\"]/div/div/form/div[2]/div[1]/div[1]/input")).clear();
 driver.findElement(By.xpath("//*[@id=\"myModal\"]/div/div/form/div[2]/div[1]/div[1]/input")).sendKeys("11Sanja");
 driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).click();
 driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).clear();
 driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).sendKeys("Sanja_Ilic@gmail.com");
 driver.findElement(By.cssSelector(".ng-untouched:nth-child(2)")).click();
 {
   WebElement dropdown = driver.findElement(By.xpath("//*[@id=\"myModal\"]/div/div/form/div[2]/div[1]/div[3]/select"));
   dropdown.findElement(By.xpath("//option[. = 'MCA']")).click();
 }
 driver.findElement(By.cssSelector(".btn-success")).click();
 driver.findElement(By.cssSelector(".btn-danger")).click();
 try {
	   Thread.sleep(4000);
	 } catch (InterruptedException e) {
	   e.printStackTrace();
	 }
}
}
